// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWrfjzK2KN2zTwNtz-4AETlabrVe9VvbA',
    appId: '1:926883909454:web:04044cb9d226e5e5fad81f',
    messagingSenderId: '926883909454',
    projectId: 'dabata-f8e26',
    authDomain: 'dabata-f8e26.firebaseapp.com',
    storageBucket: 'dabata-f8e26.firebasestorage.app',
    measurementId: 'G-9701W1ST4F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWvN5wDG2GdZi54YT2Y9qDZ11Cjzmv5Uo',
    appId: '1:926883909454:android:bc7e9d5d9961d438fad81f',
    messagingSenderId: '926883909454',
    projectId: 'dabata-f8e26',
    storageBucket: 'dabata-f8e26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQdCO7FRp9ZWA32ccYmOv_BlaiWKpFsWY',
    appId: '1:926883909454:ios:d3d994345f3413aafad81f',
    messagingSenderId: '926883909454',
    projectId: 'dabata-f8e26',
    storageBucket: 'dabata-f8e26.firebasestorage.app',
    iosBundleId: 'com.dabata',
  );

}